### ISSUE TITLE
About code environmental installation?

### ISSUE THREAD

**Issue by yuexi-wp** [huang-yh/SelfOcc#16]
Hi, thanks for your great work.
In document SelfOcc/docs/installation.md, I can't follow the step d. and step e. It shows that there is no such repository. How can I clone the git@github.com:huang-yh/sdfstudio.git and git@github.com:huang-yh/OpenSeeD.git?
Thanks a lot!

**Comment by jackwky** [comment]
How did you solve it?

**Comment by seamie6** [comment]
go to their GitHub repo and click on Code then download zip. This is essentially the same thing. I had the same issue too

**Comment by chang268** [comment]
please refer this blog https://blog.csdn.net/weixin_46535650/article/details/142617204
